# Generated by Django 4.1.5 on 2023-01-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keigoBEapp", "0002_keigo_delete_submission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="keigo",
            old_name="situation",
            new_name="situation1",
        ),
        migrations.AddField(
            model_name="keigo",
            name="situation2",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
