# Generated by Django 4.1.5 on 2023-01-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keigoBEapp", "0003_rename_situation_keigo_situation1_keigo_situation2"),
    ]

    operations = [
        migrations.AddField(
            model_name="keigo",
            name="example_translation",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
