# Generated by Django 4.1.5 on 2023-01-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("keigoBEapp", "0005_keigo_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keigo",
            name="fromWho",
        ),
        migrations.RemoveField(
            model_name="keigo",
            name="situation1",
        ),
        migrations.RemoveField(
            model_name="keigo",
            name="toWho",
        ),
    ]
